name: Automatic Deployment

on:
  schedule:
    - cron: '0 * * * *' # run every hour at minute 0

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: 'master'
    steps:
      - name: Welcome
        run: echo Start deploying tuphan.dev
      - name: Checkout git
        uses: actions/checkout@v3
      - name: Publish to Cloudflare Pages
        run: curl -X POST ${{ secrets.CLOUDFLARE_PAGES_DEPLOY_HOOK }}
